plugins {
    id "com.android.application"
}

android {
    namespace "com.prismacaja.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.prismacaja.app"
        minSdk 23
        targetSdk 35
        versionCode 28
        versionName "3.7"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation "androidx.core:core:1.13.1"
}
